import { factoryActionType } from 'utils';

const POST_REGISTRATION_STUDENT = 'POST_REGISTRATION_STUDENT';
const {
  POST_REGISTRATION_STUDENT_START,
  POST_REGISTRATION_STUDENT_SUCCESS,
  POST_REGISTRATION_STUDENT_FAIL,
} = factoryActionType([POST_REGISTRATION_STUDENT]);
const GET_REGISTRATION_DATA = 'GET_REGISTRATION_DATA';
const {
  GET_REGISTRATION_DATA_START,
  GET_REGISTRATION_DATA_SUCCESS,
  GET_REGISTRATION_DATA_FAIL,
} = factoryActionType([GET_REGISTRATION_DATA]);
const GET_LMS_GROUP_LOGO = 'GET_LMS_GROUP_LOGO';
const {
  GET_LMS_GROUP_LOGO_START,
  GET_LMS_GROUP_LOGO_SUCCESS,
  GET_LMS_GROUP_LOGO_FAIL,
} = factoryActionType([GET_LMS_GROUP_LOGO]);
const CHANGE_STUDENT_NAME = 'CHANGE_STUDENT_NAME';
const CHANGE_CONTACT_DATA = 'CHANGE_CONTACT_DATA';
const ADD_CONTACT_DATA = 'ADD_CONTACT_DATA';
const DELETE_CONTACT_DATA = 'DELETE_CONTACT_DATA';
const CHANGE_NOTIFY_DATA = 'CHANGE_NOTIFY_DATA';
const CHANGE_TAXONOMY_DATA = 'CHANGE_TAXONOMY_DATA';
const CLEAN_UP_STUDENT_DATA = 'CLEAN_UP_STUDENT_DATA';

export {
  POST_REGISTRATION_STUDENT,
  POST_REGISTRATION_STUDENT_START,
  POST_REGISTRATION_STUDENT_SUCCESS,
  POST_REGISTRATION_STUDENT_FAIL,
  GET_REGISTRATION_DATA,
  GET_REGISTRATION_DATA_START,
  GET_REGISTRATION_DATA_SUCCESS,
  GET_REGISTRATION_DATA_FAIL,
  GET_LMS_GROUP_LOGO,
  GET_LMS_GROUP_LOGO_START,
  GET_LMS_GROUP_LOGO_SUCCESS,
  GET_LMS_GROUP_LOGO_FAIL,
  CHANGE_STUDENT_NAME,
  CHANGE_CONTACT_DATA,
  ADD_CONTACT_DATA,
  DELETE_CONTACT_DATA,
  CHANGE_NOTIFY_DATA,
  CHANGE_TAXONOMY_DATA,
  CLEAN_UP_STUDENT_DATA,
};
