const GET_ALL_COMMUNICATION_REQUEST = 'GET_ALL_COMMUNICATION_REQUEST';
const GET_ALL_COMMUNICATION_START = 'GET_ALL_COMMUNICATION_START';
const GET_ALL_COMMUNICATION_SUCCESS = 'GET_ALL_COMMUNICATION_SUCCESS';
const GET_ALL_COMMUNICATION_FAIL = 'GET_ALL_COMMUNICATION_FAIL';

const GET_COURSE_COMMUNICATION_REQUEST = 'GET_COURSE_COMMUNICATION_REQUEST';
const GET_COURSE_COMMUNICATION_START = 'GET_COURSE_COMMUNICATION_START';
const GET_COURSE_COMMUNICATION_SUCCESS = 'GET_COURSE_COMMUNICATION_SUCCESS';
const GET_COURSE_COMMUNICATION_FAIL = 'GET_COURSE_COMMUNICATION_FAIL';

const ADD_COMMUNICATION_REQUEST = 'ADD_COMMUNICATION_REQUEST';
const ADD_COMMUNICATION_START = 'ADD_COMMUNICATION_START';
const ADD_COMMUNICATION_SUCCESS = 'ADD_COMMUNICATION_SUCCESS';
const ADD_COMMUNICATION_FAIL = 'ADD_COMMUNICATION_FAIL';


const GET_COMMUNICATION_DIALOG_REQUEST = 'GET_COMMUNICATION_DIALOG_REQUEST';
const GET_COMMUNICATION_DIALOG_START = 'GET_COMMUNICATION_DIALOG_START';
const GET_COMMUNICATION_DIALOG_SUCCESS = 'GET_COMMUNICATION_DIALOG_SUCCESS';
const GET_COMMUNICATION_DIALOG_FAIL = 'GET_COMMUNICATION_DIALOG_FAIL';

const PUT_COMMUNICATION_SEARCH_REQUEST = 'PUT_COMMUNICATION_SEARCH_REQUEST';
const PUT_COMMUNICATION_SEARCH_START = 'PUT_COMMUNICATION_SEARCH_START';
const PUT_COMMUNICATION_SEARCH_SUCCESS = 'PUT_COMMUNICATION_SEARCH_SUCCESS';
const PUT_COMMUNICATION_SEARCH_FAIL = 'PUT_COMMUNICATION_SEARCH_FAIL';

const ADD_COMMUNICATION_DIALOG_REQUEST = 'ADD_COMMUNICATION_DIALOG_REQUEST';
const ADD_COMMUNICATION_DIALOG_START = 'ADD_COMMUNICATION_DIALOG_START';
const ADD_COMMUNICATION_DIALOG_SUCCESS = 'ADD_COMMUNICATION_DIALOG_SUCCESS';
const ADD_COMMUNICATION_DIALOG_FAIL = 'ADD_COMMUNICATION_DIALOG_FAIL';

const SET_COURSE_COMMUNICATION_ID = 'SET_COURSE_COMMUNICATION_ID';
const SET_COMMUNICATION_ID = 'SET_COMMUNICATION_ID';
const SET_COMMUNICATION_DIALOG_ID = 'SET_COMMUNICATION_DIALOG_ID';

const PUT_COMMUNICATION_IS_READ_REQUEST = 'PUT_COMMUNICATION_IS_READ_REQUEST';
const PUT_COMMUNICATION_IS_READ_START = 'PUT_COMMUNICATION_IS_READ_START';
const PUT_COMMUNICATION_IS_READ_SUCCESS = 'PUT_COMMUNICATION_IS_READ_SUCCESS';
const PUT_COMMUNICATION_IS_READ_FAIL = 'PUT_COMMUNICATION_IS_READ_FAIL';

const SET_QUEST_STATUS = 'SET_QUEST_STATUS';
const OPEN_ALL_QUESTS = 'OPEN_ALL_QUESTS';
const CLICK_QUEST_REQUEST = 'CLICK_QUEST_REQUEST';

const DELETE_LAST_MESSAGE = 'DELETE_LAST_MESSAGE';
const DELETE_LAST_MESSAGE_START = 'DELETE_LAST_MESSAGE_START';
const DELETE_LAST_MESSAGE_SUCCESS = 'DELETE_LAST_MESSAGE_SUCCESS';
const DELETE_LAST_MESSAGE_ERROR = 'DELETE_LAST_MESSAGE_ERROR';

const CLOSE_ALL_DIALOG = 'CLOSE_ALL_DIALOG';

const CLEAR_COMMUNICATION = 'CLEAR_COMMUNICATION';

export default {
  GET_ALL_COMMUNICATION_REQUEST,
  GET_ALL_COMMUNICATION_START,
  GET_ALL_COMMUNICATION_SUCCESS,
  GET_ALL_COMMUNICATION_FAIL,
  GET_COURSE_COMMUNICATION_REQUEST,
  GET_COURSE_COMMUNICATION_START,
  GET_COURSE_COMMUNICATION_SUCCESS,
  GET_COURSE_COMMUNICATION_FAIL,
  ADD_COMMUNICATION_REQUEST,
  ADD_COMMUNICATION_START,
  ADD_COMMUNICATION_SUCCESS,
  ADD_COMMUNICATION_FAIL,
  GET_COMMUNICATION_DIALOG_REQUEST,
  GET_COMMUNICATION_DIALOG_START,
  GET_COMMUNICATION_DIALOG_SUCCESS,
  GET_COMMUNICATION_DIALOG_FAIL,
  ADD_COMMUNICATION_DIALOG_REQUEST,
  ADD_COMMUNICATION_DIALOG_START,
  ADD_COMMUNICATION_DIALOG_SUCCESS,
  ADD_COMMUNICATION_DIALOG_FAIL,
  PUT_COMMUNICATION_SEARCH_REQUEST,
  PUT_COMMUNICATION_SEARCH_START,
  PUT_COMMUNICATION_SEARCH_SUCCESS,
  PUT_COMMUNICATION_SEARCH_FAIL,
  SET_COURSE_COMMUNICATION_ID,
  SET_COMMUNICATION_ID,
  SET_COMMUNICATION_DIALOG_ID,
  PUT_COMMUNICATION_IS_READ_REQUEST,
  PUT_COMMUNICATION_IS_READ_START,
  PUT_COMMUNICATION_IS_READ_SUCCESS,
  PUT_COMMUNICATION_IS_READ_FAIL,
  SET_QUEST_STATUS,
  OPEN_ALL_QUESTS,
  CLICK_QUEST_REQUEST,
  DELETE_LAST_MESSAGE,
  DELETE_LAST_MESSAGE_START,
  DELETE_LAST_MESSAGE_SUCCESS,
  DELETE_LAST_MESSAGE_ERROR,
  CLOSE_ALL_DIALOG,
  CLEAR_COMMUNICATION,
};
